ePixBoard:
  enable: True
  ForceWrite: False
  InitAfterConfig: False
  PollEn: False
  dataWriter:
    enable: True
    dataFile: ''
    open: False
    bufferSize: 0
    maxFileSize: 0
  Epix10ka:
    enable: True
    AxiVersion:
      enable: True
      ScratchPad: 0x000000
      FpgaReloadHalt: 0x0
      FpgaReloadAddress: 0x0
      UserReset: 0x0
    EpixFpgaRegisters:
      enable: True
      RunTriggerEnable: True
      RunTriggerDelay: 0x0
      RunTriggerDelayUs: 0.00000
      DaqTriggerEnable: True
      DaqTriggerDelay: 0x0
      DaqTriggerDelayUs: 0.00000
      AcqCountReset: False
      DacData: 0x0
      DigitalPowerEnable: True
      AnalogPowerEnable: True
      FpgaOutputEnable: True
      IDelayCtrlRdy: 0x1
      SeqCountReset: False
      AutoRunEnable: False
      AutoRunPeriod: 0x107d99
      AutoRunPeriodMs: 8.33333
      AutoDaqEnable: False
      AcqToAsicR0Delay: 0x0
      AcqToAsicR0DelayUs: 0.00000
      AsicR0ToAsicAcq: 0x32a9
      AsicR0ToAsicAcqUs: 100.00193
      AsicAcqWidth: 0x32a9
      AsicAcqWidthUs: 100.00193
      AsicAcqLToPPmatL: 0xc8
      AsicAcqLToPPmatLUs: 1.54217
      AsicRoClkT: 0xc
      AdcClkHalfT: 0x1
      TotalPixelsToRead: 0x8580
      AsicGR: False
      AsicAcq: False
      AsicRO: False
      AsicPpmat: True
      AsicPpbe: False
      AsicRoClk: False
      AsicPinGRControl: False
      AsicPinAcqControl: False
      AsicPinROControl: False
      AsicPinPpmatControl: True
      AsicPinPpbeControl: False
      AsicPinROClkControl: False
      AdcPatternEnable: False
      AsicR0Width: 0x1e
      AsicR0WidthUs: 0.23133
      AsicPPmatToReadout: 0x0
      AsicPPmatToReadoutUs: 0.00000
      PgpTrigEn: False
      RequestStartup: False
      AdcPipelineDelayA0: 0x2c
      AdcPipelineDelayA1: 0x2c
      AdcPipelineDelayA2: 0x2c
      AdcPipelineDelayA3: 0x2c
    EpixFpgaExtRegisters:
      enable: True
      GhostCorrEn: False
      OversampleEn: True
      OversampleSize: 0x3
      DebugOut: 0x3
      InjStartDly: 0x0
      InjStartDlyUs: 0.00000
      InjStopDly: 0x0
      InjStopDlyUs: 0.00000
      InjSkip: 0x0
      BankPipelineDly00: 0x2c
      BankPipelineDly01: 0x2c
      BankPipelineDly02: 0x2c
      BankPipelineDly03: 0x2c
      BankPipelineDly04: 0x2c
      BankPipelineDly05: 0x2c
      BankPipelineDly06: 0x2c
      BankPipelineDly07: 0x2c
      BankPipelineDly08: 0x2c
      BankPipelineDly09: 0x2c
      BankPipelineDly10: 0x2c
      BankPipelineDly11: 0x2c
      BankPipelineDly12: 0x2c
      BankPipelineDly13: 0x2c
      BankPipelineDly14: 0x2c
      BankPipelineDly15: 0x2c
    Oscilloscope:
      enable: True
      ArmReg: False
      TrigReg: False
      ScopeEnable: False
      TriggerEdge: Rising
      TriggerChannel: AsicRoClk
      TriggerMode: AcqStart
      TriggerAdcThresh: 9000
      TriggerHoldoff: 0
      TriggerOffset: 0
      TraceLength: 50
      SkipSamples: 0
      InputChannelA: ASIC1_B0
      InputChannelB: ASIC0_B0
      TriggerDelay: 2970
    Epix10kADouts:
      enable: True
      RdoutClkDelay: 0xa
      SystemClkDelay: 0x0
      RdoutOrder: 0xff0
    Epix10kaAsic[0]:
      enable: True
      CompTH_DAC: 0x22
      CompEn0: False
      CompEn1: True
      CompEn2: True
      PulserSync: False
      PixelDummy: 0x22
      Pulser: 0xc8
      pbit: False
      atest: False
      test: True
      sab_test: False
      hrtest: False
      PulserR: False
      DigMon1: 0x0
      DigMon2: 0x1
      PulserDac: 0x3
      MonostPulser: 0x0
      Dm1En: False
      Dm2En: False
      emph_bd: 0x0
      emph_bc: 0x0
      VRef: 0x13
      VRefLow: 0x3
      TpsTComp: True
      TpsMux: 0x0
      RoMonost: 0x3
      TpsGr: 0x3
      S2d0Gr: 0x3
      PpOcbS2d: True
      Ocb: 0x0
      Monost: 0x3
      FastppEnable: False
      Preamp: 0x4
      PixelCb: 0x4
      Vld1_b: 0x1
      S2dTComp: False
      FilterDac: 0x11
      TestLVDTransmitter: False
      TC: 0x0
      S2d: 0x0
      S2dDacBias: 0x3
      TpsTcDac: 0x0
      TpsDac: 0x10
      S2d0TcDac: 0x1
      S2d0Dac: 0x14
      TestBe: False
      IsEn: False
      DelExec: False
      DelCckRef: False
      RO_rst_en: True
      SlvdsBit: True
      FELmode: True
      CompEnOn: False
      RowStartAddr: 0x0
      RowStopAddr: 0xb1
      ColStartAddr: 0x0
      ColStopAddr: 0x2f
      S2d1Gr: 0x3
      S2d2Gr: 0x3
      S2d3Gr: 0x3
      trbit: True
      S2d1TcDac: 0x1
      S2d1Dac: 0x12
      S2d2TcDac: 0x1
      S2d2Dac: 0x12
      S2d3TcDac: 0x1
      S2d3Dac: 0x12
    Epix10kaAsic[1]:
      enable: True
      CompTH_DAC: 0x22
      CompEn0: False
      CompEn1: True
      CompEn2: True
      PulserSync: False
      PixelDummy: 0x22
      Pulser: 0x0
      pbit: False
      atest: False
      test: False
      sab_test: False
      hrtest: False
      PulserR: False
      DigMon1: 0x0
      DigMon2: 0x1
      PulserDac: 0x3
      MonostPulser: 0x0
      Dm1En: False
      Dm2En: False
      emph_bd: 0x0
      emph_bc: 0x0
      VRef: 0x13
      VRefLow: 0x3
      TpsTComp: True
      TpsMux: 0x0
      RoMonost: 0x3
      TpsGr: 0x3
      S2d0Gr: 0x3
      PpOcbS2d: True
      Ocb: 0x0
      Monost: 0x3
      FastppEnable: False
      Preamp: 0x4
      PixelCb: 0x4
      Vld1_b: 0x1
      S2dTComp: False
      FilterDac: 0x11
      TestLVDTransmitter: False
      TC: 0x0
      S2d: 0x0
      S2dDacBias: 0x3
      TpsTcDac: 0x0
      TpsDac: 0x10
      S2d0TcDac: 0x1
      S2d0Dac: 0x14
      TestBe: False
      IsEn: False
      DelExec: False
      DelCckRef: False
      RO_rst_en: True
      SlvdsBit: True
      FELmode: True
      CompEnOn: False
      RowStartAddr: 0x0
      RowStopAddr: 0xb1
      ColStartAddr: 0x0
      ColStopAddr: 0x2f
      S2d1Gr: 0x3
      S2d2Gr: 0x3
      S2d3Gr: 0x3
      trbit: True
      S2d1TcDac: 0x1
      S2d1Dac: 0x12
      S2d2TcDac: 0x1
      S2d2Dac: 0x12
      S2d3TcDac: 0x1
      S2d3Dac: 0x12
    Epix10kaAsic[2]:
      enable: True
      CompTH_DAC: 0x22
      CompEn0: False
      CompEn1: True
      CompEn2: True
      PulserSync: False
      PixelDummy: 0x22
      Pulser: 0x0
      pbit: False
      atest: False
      test: False
      sab_test: False
      hrtest: False
      PulserR: False
      DigMon1: 0x0
      DigMon2: 0x1
      PulserDac: 0x3
      MonostPulser: 0x0
      Dm1En: False
      Dm2En: False
      emph_bd: 0x0
      emph_bc: 0x0
      VRef: 0x13
      VRefLow: 0x3
      TpsTComp: True
      TpsMux: 0x0
      RoMonost: 0x3
      TpsGr: 0x3
      S2d0Gr: 0x3
      PpOcbS2d: True
      Ocb: 0x0
      Monost: 0x3
      FastppEnable: False
      Preamp: 0x4
      PixelCb: 0x4
      Vld1_b: 0x1
      S2dTComp: False
      FilterDac: 0x11
      TestLVDTransmitter: False
      TC: 0x0
      S2d: 0x0
      S2dDacBias: 0x3
      TpsTcDac: 0x0
      TpsDac: 0x10
      S2d0TcDac: 0x1
      S2d0Dac: 0x14
      TestBe: False
      IsEn: False
      DelExec: False
      DelCckRef: False
      RO_rst_en: True
      SlvdsBit: True
      FELmode: True
      CompEnOn: False
      RowStartAddr: 0x0
      RowStopAddr: 0xb1
      ColStartAddr: 0x0
      ColStopAddr: 0x2f
      S2d1Gr: 0x3
      S2d2Gr: 0x3
      S2d3Gr: 0x3
      trbit: True
      S2d1TcDac: 0x1
      S2d1Dac: 0x12
      S2d2TcDac: 0x1
      S2d2Dac: 0x12
      S2d3TcDac: 0x1
      S2d3Dac: 0x12
    Epix10kaAsic[3]:
      enable: True
      CompTH_DAC: 0x22
      CompEn0: False
      CompEn1: True
      CompEn2: True
      PulserSync: False
      PixelDummy: 0x22
      Pulser: 0x0
      pbit: False
      atest: False
      test: False
      sab_test: False
      hrtest: False
      PulserR: False
      DigMon1: 0x0
      DigMon2: 0x1
      PulserDac: 0x3
      MonostPulser: 0x0
      Dm1En: False
      Dm2En: False
      emph_bd: 0x0
      emph_bc: 0x0
      VRef: 0x13
      VRefLow: 0x3
      TpsTComp: True
      TpsMux: 0x0
      RoMonost: 0x3
      TpsGr: 0x3
      S2d0Gr: 0x3
      PpOcbS2d: True
      Ocb: 0x0
      Monost: 0x3
      FastppEnable: False
      Preamp: 0x4
      PixelCb: 0x4
      Vld1_b: 0x1
      S2dTComp: False
      FilterDac: 0x11
      TestLVDTransmitter: False
      TC: 0x0
      S2d: 0x0
      S2dDacBias: 0x3
      TpsTcDac: 0x0
      TpsDac: 0x10
      S2d0TcDac: 0x1
      S2d0Dac: 0x14
      TestBe: False
      IsEn: False
      DelExec: False
      DelCckRef: False
      RO_rst_en: True
      SlvdsBit: True
      FELmode: True
      CompEnOn: False
      RowStartAddr: 0x0
      RowStopAddr: 0xb1
      ColStartAddr: 0x0
      ColStopAddr: 0x2f
      S2d1Gr: 0x3
      S2d2Gr: 0x3
      S2d3Gr: 0x3
      trbit: True
      S2d1TcDac: 0x1
      S2d1Dac: 0x12
      S2d2TcDac: 0x1
      S2d2Dac: 0x12
      S2d3TcDac: 0x1
      S2d3Dac: 0x12
    Pgp3Axi:
      enable: False
      AutoStatus: False
      SkipInterval: 0
    SlowAdcRegisters:
      enable: False
      StreamEn: False
      StreamPeriod: 0
    Ad9249RdoutAdc[0]:
      enable: False
      ChannelDelay[0]: 0x0
      ChannelDelay[1]: 0x0
      ChannelDelay[2]: 0x0
      ChannelDelay[3]: 0x0
      ChannelDelay[4]: 0x0
      ChannelDelay[5]: 0x0
      ChannelDelay[6]: 0x0
      ChannelDelay[7]: 0x0
      FrameDelay: 0x0
      Invert: False
    Ad9249RdoutAdc[1]:
      enable: False
      ChannelDelay[0]: 0x0
      ChannelDelay[1]: 0x0
      ChannelDelay[2]: 0x0
      ChannelDelay[3]: 0x0
      ChannelDelay[4]: 0x0
      ChannelDelay[5]: 0x0
      ChannelDelay[6]: 0x0
      ChannelDelay[7]: 0x0
      FrameDelay: 0x0
      Invert: False
    Ad9249RdoutAdc[2]:
      enable: False
      ChannelDelay[0]: 0x0
      ChannelDelay[1]: 0x0
      ChannelDelay[2]: 0x0
      ChannelDelay[3]: 0x0
      FrameDelay: 0x0
      Invert: False
    Ad9249ConfigAdc[0]:
      enable: False
      ExternalPdwnMode: Full Power Down
      InternalPdwnMode: Chip Run
      DutyCycleStabilizer: 'Off'
      ClockDivide: Divide by 1
      ChopMode: 'Off'
      DevIndexMask[7:0]: 0b0
      DevIndexMask[DCO:FCO]: 0b0
      UserTestModeCfg: single
      OutputTestMode: 'Off'
      OffsetAdjust: 0x0
      OutputInvert: False
      OutputFormat: Offset Binary
      UserPatt1Lsb: 0x0
      UserPatt1Msb: 0x0
      UserPatt2Lsb: 0x0
      UserPatt2Msb: 0x0
      LvdsLsbFirst: False
    Ad9249ConfigAdc[1]:
      enable: False
      ExternalPdwnMode: Full Power Down
      InternalPdwnMode: Chip Run
      DutyCycleStabilizer: 'Off'
      ClockDivide: Divide by 1
      ChopMode: 'Off'
      DevIndexMask[7:0]: 0b0
      DevIndexMask[DCO:FCO]: 0b0
      UserTestModeCfg: single
      OutputTestMode: 'Off'
      OffsetAdjust: 0x0
      OutputInvert: False
      OutputFormat: Offset Binary
      UserPatt1Lsb: 0x0
      UserPatt1Msb: 0x0
      UserPatt2Lsb: 0x0
      UserPatt2Msb: 0x0
      LvdsLsbFirst: False
    Ad9249ConfigAdc[2]:
      enable: False
      ExternalPdwnMode: Full Power Down
      InternalPdwnMode: Chip Run
      DutyCycleStabilizer: 'Off'
      ClockDivide: Divide by 1
      ChopMode: 'Off'
      DevIndexMask[7:0]: 0b0
      DevIndexMask[DCO:FCO]: 0b0
      UserTestModeCfg: single
      OutputTestMode: 'Off'
      OffsetAdjust: 0x0
      OutputInvert: False
      OutputFormat: Offset Binary
      UserPatt1Lsb: 0x0
      UserPatt1Msb: 0x0
      UserPatt2Lsb: 0x0
      UserPatt2Msb: 0x0
      LvdsLsbFirst: False
    MicronN25Q:
      enable: True
    MicroblazeLog:
      enable: False
  runControl:
    enable: True
    runState: Stopped
    runRate: 1 Hz
