Top:
  enable: True
  ForceWrite: False
  InitAfterConfig: False
  PollEn: False
  PrbsRx:
    enable: True
    checkPayload: True
  AxiVersion:
    enable: True
    ScratchPad: 0x000000
    FpgaReloadHalt: 0x0
    FpgaReloadAddress: 0x0
    UserReset: 0x0
  SystemRegs:
    enable: True
    UsrRst: 0x0
    TrigEn: True
    TrigSrcSel: 0x3
    TrigPeriodRst: False
    AutoTrigEn: True
    AutoTrigPer: 0x22ADD
    AutoTrigPerMs: 0.90000
    AutoTrigFreqHz: 1100.0
    DcDcEnable: 0xf
    AsicAnaEn: True
    AsicDigEn: True
    AdcClkRst: 0x0
    AdcReqStart: False
    AdcReqTest: False
    AdcTestDone: True
    AdcTestFailed: False
    Adc[0]ChannelFail: 0x0
    Adc[1]ChannelFail: 0x0
    Adc[2]ChannelFail: 0x0
    Adc[3]ChannelFail: 0x0
    Adc[4]ChannelFail: 0x0
    Adc[5]ChannelFail: 0x0
    Adc[6]ChannelFail: 0x0
    Adc[7]ChannelFail: 0x0
    Adc[8]ChannelFail: 0x0
    Adc[9]ChannelFail: 0x0
    AdcBypass: False
    DdrVttEn: False
    LatchTempFault: True
    CarrierIdRst: False
  AcqCore:
    enable: True
    AcqCountReset: False
    AcqToAsicR0Delay: 0x0
    AsicR0Width: 0x1e
    AsicR0ToAsicAcq: 0x700
    AsicAcqWidth: 0x700
    AsicAcqLToPPmatL: 0x3e8
    AsicPpmatToReadout: 0x0
    AsicRoClkT: 0xaaaa0004
    AsicAcqForce: False
    AsicR0Force: False
    AsicPpmatForce: True
    AsicSyncForce: False
    AsicRoClkForce: False
    AsicAcqValue: False
    AsicR0Value: False
    AsicPpmatValue: True
    AsicSyncValue: False
    AsicRoClkValue: False
    DummyAcqEn: False
    AsicSyncInjEn: True
    AsicSyncInjDly: 0x3e8
    DbgOutSel[0]: 0x0
    DbgOutSel[1]: 0x0
    DbgOutSel[2]: 0x0
  RdoutCore:
    enable: True
    RdoutEn: True
    SeqCountReset: False
    AdcPipelineDelay: 0x5a
  RdoutStreamMonitoring:
    enable: True
    Ch[0]:
      enable: True
  PrbsTx:
    enable: False
    AxiEn: False
    TxEn: False
    FwCnt: False
    PacketLength: 0x0
    tDest: 0x0
    tId: 0x0
    TrigDly: 0x0
  PseudoScopeCore:
    enable: True
    Arm: False
    Trig: False
    ScopeEn: False
    TrigEdge: False
    TrigChannel: 0x4
    TrigMode: 0x2
    TrigAdcThreshold: 0x0
    TrigOffset: 0x46a
    TraceLength: 0x1f40
    SkipSamples: 0x0
    InChannelA: 0x10
    InChannelB: 0x11
    TrigDelay: 0x0
  VguardDac:
    enable: True
    VguardDacRaw: 0x0
    VguardDacVolt: 0.00000
  EpixQuadMonitor:
    enable: True
    MonitorEn: True
    TrigPrescaler: 0x0
  AxiMemTester:
    enable: False
  Epix10kaSaci[15]:
    enable: True
    CompTH_DAC: 0x22
    CompEn0: False
    CompEn1: True
    CompEn2: True
    PulserSync: True
    Pulser: 0x0
    pbit: False
    atest: False
    test: False
    sab_test: False
    hrtest: False
    PulserR: False
    DigMon1: 0x0
    DigMon2: 0x1
    PulserDac: 0x3
    MonostPulser: 0x0
    Dm1En: False
    Dm2En: False
    emph_bd: 0x0
    emph_bc: 0x0
    VRef: 0x13
    VRefLow: 0x3
    TpsTComp: True
    TpsMux: 0x0
    RoMonost: 0x3
    TpsGr: 0x3
    S2d0Gr: 0x3
    PpOcbS2d: True
    Ocb: 0x3
    Monost: 0x3
    FastppEnable: False
    Preamp: 0x4
    PixelCb: 0x4
    Vld1_b: 0x1
    S2dTComp: False
    FilterDac: 0x11
    TestLVDTransmitter: False
    TC: 0x0
    S2d: 0x3
    S2dDacBias: 0x3
    TpsTcDac: 0x0
    TpsDac: 0x10
    S2d0TcDac: 0x1
    S2d0Dac: 0x14
    TestBe: False
    IsEn: False
    DelExec: False
    DelCckRef: False
    RO_rst_en: True
    SlvdsBit: True
    FELmode: True
    CompEnOn: False
    RowStartAddr: 0x0
    RowStopAddr: 0xb1
    ColStartAddr: 0x0
    ColStopAddr: 0x2f
    S2d1Gr: 0x3
    S2d2Gr: 0x3
    S2d3Gr: 0x3
    trbit: False
    S2d1TcDac: 0x1
    S2d1Dac: 0x12
    S2d2TcDac: 0x1
    S2d2Dac: 0x12
    S2d3TcDac: 0x1
    S2d3Dac: 0x12
  Epix10kaSaci[14]:
    enable: True
    CompTH_DAC: 0x22
    CompEn0: False
    CompEn1: True
    CompEn2: True
    PulserSync: True
    Pulser: 0x0
    pbit: False
    atest: False
    test: False
    sab_test: False
    hrtest: False
    PulserR: False
    DigMon1: 0x0
    DigMon2: 0x1
    PulserDac: 0x3
    MonostPulser: 0x0
    Dm1En: False
    Dm2En: False
    emph_bd: 0x0
    emph_bc: 0x0
    VRef: 0x13
    VRefLow: 0x3
    TpsTComp: True
    TpsMux: 0x0
    RoMonost: 0x3
    TpsGr: 0x3
    S2d0Gr: 0x3
    PpOcbS2d: True
    Ocb: 0x3
    Monost: 0x3
    FastppEnable: False
    Preamp: 0x4
    PixelCb: 0x4
    Vld1_b: 0x1
    S2dTComp: False
    FilterDac: 0x11
    TestLVDTransmitter: False
    TC: 0x0
    S2d: 0x3
    S2dDacBias: 0x3
    TpsTcDac: 0x0
    TpsDac: 0x10
    S2d0TcDac: 0x1
    S2d0Dac: 0x14
    TestBe: False
    IsEn: False
    DelExec: False
    DelCckRef: False
    RO_rst_en: True
    SlvdsBit: True
    FELmode: True
    CompEnOn: False
    RowStartAddr: 0x0
    RowStopAddr: 0xb1
    ColStartAddr: 0x0
    ColStopAddr: 0x2f
    S2d1Gr: 0x3
    S2d2Gr: 0x3
    S2d3Gr: 0x3
    trbit: False
    S2d1TcDac: 0x1
    S2d1Dac: 0x12
    S2d2TcDac: 0x1
    S2d2Dac: 0x12
    S2d3TcDac: 0x1
    S2d3Dac: 0x12
  Epix10kaSaci[13]:
    enable: True
    CompTH_DAC: 0x22
    CompEn0: False
    CompEn1: True
    CompEn2: True
    PulserSync: True
    Pulser: 0x0
    pbit: False
    atest: False
    test: False
    sab_test: False
    hrtest: False
    PulserR: False
    DigMon1: 0x0
    DigMon2: 0x1
    PulserDac: 0x3
    MonostPulser: 0x0
    Dm1En: False
    Dm2En: False
    emph_bd: 0x0
    emph_bc: 0x0
    VRef: 0x13
    VRefLow: 0x3
    TpsTComp: True
    TpsMux: 0x0
    RoMonost: 0x3
    TpsGr: 0x3
    S2d0Gr: 0x3
    PpOcbS2d: True
    Ocb: 0x3
    Monost: 0x3
    FastppEnable: False
    Preamp: 0x4
    PixelCb: 0x4
    Vld1_b: 0x1
    S2dTComp: False
    FilterDac: 0x11
    TestLVDTransmitter: False
    TC: 0x0
    S2d: 0x3
    S2dDacBias: 0x3
    TpsTcDac: 0x0
    TpsDac: 0x10
    S2d0TcDac: 0x1
    S2d0Dac: 0x14
    TestBe: False
    IsEn: False
    DelExec: False
    DelCckRef: False
    RO_rst_en: True
    SlvdsBit: True
    FELmode: True
    CompEnOn: False
    RowStartAddr: 0x0
    RowStopAddr: 0xb1
    ColStartAddr: 0x0
    ColStopAddr: 0x2f
    S2d1Gr: 0x3
    S2d2Gr: 0x3
    S2d3Gr: 0x3
    trbit: False
    S2d1TcDac: 0x1
    S2d1Dac: 0x12
    S2d2TcDac: 0x1
    S2d2Dac: 0x12
    S2d3TcDac: 0x1
    S2d3Dac: 0x12
  Epix10kaSaci[12]:
    enable: True
    CompTH_DAC: 0x22
    CompEn0: False
    CompEn1: True
    CompEn2: True
    PulserSync: True
    Pulser: 0x200
    pbit: False
    atest: False
    test: False
    sab_test: False
    hrtest: False
    PulserR: False
    DigMon1: 0x0
    DigMon2: 0x1
    PulserDac: 0x3
    MonostPulser: 0x4
    Dm1En: False
    Dm2En: False
    emph_bd: 0x0
    emph_bc: 0x0
    VRef: 0x13
    VRefLow: 0x3
    TpsTComp: True
    TpsMux: 0x0
    RoMonost: 0x3
    TpsGr: 0x3
    S2d0Gr: 0x3
    PpOcbS2d: True
    Ocb: 0x3
    Monost: 0x3
    FastppEnable: False
    Preamp: 0x4
    PixelCb: 0x4
    Vld1_b: 0x1
    S2dTComp: False
    FilterDac: 0x11
    TestLVDTransmitter: False
    TC: 0x0
    S2d: 0x3
    S2dDacBias: 0x3
    TpsTcDac: 0x0
    TpsDac: 0x10
    S2d0TcDac: 0x1
    S2d0Dac: 0x14
    TestBe: False
    IsEn: False
    DelExec: False
    DelCckRef: False
    RO_rst_en: True
    SlvdsBit: True
    FELmode: True
    CompEnOn: True
    RowStartAddr: 0x0
    RowStopAddr: 0xb1
    ColStartAddr: 0x0
    ColStopAddr: 0x2f
    S2d1Gr: 0x3
    S2d2Gr: 0x3
    S2d3Gr: 0x3
    trbit: False
    S2d1TcDac: 0x1
    S2d1Dac: 0x12
    S2d2TcDac: 0x1
    S2d2Dac: 0x12
    S2d3TcDac: 0x1
    S2d3Dac: 0x12
  SaciConfigCore:
    enable: False
    ConfWrReq: False
    ConfRdReq: False
    ConfSel: 0x0
  Ad9249Config[0]:
    enable: False
    ExternalPdwnMode: Full Power Down
    InternalPdwnMode: Chip Run
    DutyCycleStabilizer: 'Off'
    ClockDivide: Divide by 1
    ChopMode: 'Off'
    UserTestModeCfg: single
    OutputTestMode: 'Off'
    OffsetAdjust: 0x0
    OutputInvert: False
    OutputFormat: Offset Binary
    UserPatt1Lsb: 0x0
    UserPatt1Msb: 0x0
    UserPatt2Lsb: 0x0
    UserPatt2Msb: 0x0
    LvdsLsbFirst: False
  Ad9249Config[1]:
    enable: False
    ExternalPdwnMode: Full Power Down
    InternalPdwnMode: Chip Run
    DutyCycleStabilizer: 'Off'
    ClockDivide: Divide by 1
    ChopMode: 'Off'
    UserTestModeCfg: single
    OutputTestMode: 'Off'
    OffsetAdjust: 0x0
    OutputInvert: False
    OutputFormat: Offset Binary
    UserPatt1Lsb: 0x0
    UserPatt1Msb: 0x0
    UserPatt2Lsb: 0x0
    UserPatt2Msb: 0x0
    LvdsLsbFirst: False
  Ad9249Config[2]:
    enable: False
    ExternalPdwnMode: Full Power Down
    InternalPdwnMode: Chip Run
    DutyCycleStabilizer: 'Off'
    ClockDivide: Divide by 1
    ChopMode: 'Off'
    UserTestModeCfg: single
    OutputTestMode: 'Off'
    OffsetAdjust: 0x0
    OutputInvert: False
    OutputFormat: Offset Binary
    UserPatt1Lsb: 0x0
    UserPatt1Msb: 0x0
    UserPatt2Lsb: 0x0
    UserPatt2Msb: 0x0
    LvdsLsbFirst: False
  Ad9249Config[3]:
    enable: False
    ExternalPdwnMode: Full Power Down
    InternalPdwnMode: Chip Run
    DutyCycleStabilizer: 'Off'
    ClockDivide: Divide by 1
    ChopMode: 'Off'
    UserTestModeCfg: single
    OutputTestMode: 'Off'
    OffsetAdjust: 0x0
    OutputInvert: False
    OutputFormat: Offset Binary
    UserPatt1Lsb: 0x0
    UserPatt1Msb: 0x0
    UserPatt2Lsb: 0x0
    UserPatt2Msb: 0x0
    LvdsLsbFirst: False
  Ad9249Config[4]:
    enable: False
    ExternalPdwnMode: Full Power Down
    InternalPdwnMode: Chip Run
    DutyCycleStabilizer: 'Off'
    ClockDivide: Divide by 1
    ChopMode: 'Off'
    UserTestModeCfg: single
    OutputTestMode: 'Off'
    OffsetAdjust: 0x0
    OutputInvert: False
    OutputFormat: Offset Binary
    UserPatt1Lsb: 0x0
    UserPatt1Msb: 0x0
    UserPatt2Lsb: 0x0
    UserPatt2Msb: 0x0
    LvdsLsbFirst: False
  Ad9249Config[5]:
    enable: False
    ExternalPdwnMode: Full Power Down
    InternalPdwnMode: Chip Run
    DutyCycleStabilizer: 'Off'
    ClockDivide: Divide by 1
    ChopMode: 'Off'
    UserTestModeCfg: single
    OutputTestMode: 'Off'
    OffsetAdjust: 0x0
    OutputInvert: False
    OutputFormat: Offset Binary
    UserPatt1Lsb: 0x0
    UserPatt1Msb: 0x0
    UserPatt2Lsb: 0x0
    UserPatt2Msb: 0x0
    LvdsLsbFirst: False
  Ad9249Config[6]:
    enable: False
    ExternalPdwnMode: Full Power Down
    InternalPdwnMode: Chip Run
    DutyCycleStabilizer: 'Off'
    ClockDivide: Divide by 1
    ChopMode: 'Off'
    UserTestModeCfg: single
    OutputTestMode: 'Off'
    OffsetAdjust: 0x0
    OutputInvert: False
    OutputFormat: Offset Binary
    UserPatt1Lsb: 0x0
    UserPatt1Msb: 0x0
    UserPatt2Lsb: 0x0
    UserPatt2Msb: 0x0
    LvdsLsbFirst: False
  Ad9249Config[7]:
    enable: False
    ExternalPdwnMode: Full Power Down
    InternalPdwnMode: Chip Run
    DutyCycleStabilizer: 'Off'
    ClockDivide: Divide by 1
    ChopMode: 'Off'
    UserTestModeCfg: single
    OutputTestMode: 'Off'
    OffsetAdjust: 0x0
    OutputInvert: False
    OutputFormat: Offset Binary
    UserPatt1Lsb: 0x0
    UserPatt1Msb: 0x0
    UserPatt2Lsb: 0x0
    UserPatt2Msb: 0x0
    LvdsLsbFirst: False
  Ad9249Config[8]:
    enable: False
    ExternalPdwnMode: Full Power Down
    InternalPdwnMode: Chip Run
    DutyCycleStabilizer: 'Off'
    ClockDivide: Divide by 1
    ChopMode: 'Off'
    UserTestModeCfg: single
    OutputTestMode: 'Off'
    OffsetAdjust: 0x0
    OutputInvert: False
    OutputFormat: Offset Binary
    UserPatt1Lsb: 0x0
    UserPatt1Msb: 0x0
    UserPatt2Lsb: 0x0
    UserPatt2Msb: 0x0
    LvdsLsbFirst: False
  Ad9249Config[9]:
    enable: False
    ExternalPdwnMode: Full Power Down
    InternalPdwnMode: Chip Run
    DutyCycleStabilizer: 'Off'
    ClockDivide: Divide by 1
    ChopMode: 'Off'
    UserTestModeCfg: single
    OutputTestMode: 'Off'
    OffsetAdjust: 0x0
    OutputInvert: False
    OutputFormat: Offset Binary
    UserPatt1Lsb: 0x0
    UserPatt1Msb: 0x0
    UserPatt2Lsb: 0x0
    UserPatt2Msb: 0x0
    LvdsLsbFirst: False
  Ad9249Readout[0]:
    enable: False
    ChannelDelay[0]: 0x0
    ChannelDelay[1]: 0x0
    ChannelDelay[2]: 0x0
    ChannelDelay[3]: 0x0
    ChannelDelay[4]: 0x0
    ChannelDelay[5]: 0x0
    ChannelDelay[6]: 0x0
    ChannelDelay[7]: 0x0
    FrameDelay: 0x0
    Invert: False
  Ad9249Readout[1]:
    enable: False
    ChannelDelay[0]: 0x0
    ChannelDelay[1]: 0x0
    ChannelDelay[2]: 0x0
    ChannelDelay[3]: 0x0
    ChannelDelay[4]: 0x0
    ChannelDelay[5]: 0x0
    ChannelDelay[6]: 0x0
    ChannelDelay[7]: 0x0
    FrameDelay: 0x0
    Invert: False
  Ad9249Readout[2]:
    enable: False
    ChannelDelay[0]: 0x0
    ChannelDelay[1]: 0x0
    ChannelDelay[2]: 0x0
    ChannelDelay[3]: 0x0
    ChannelDelay[4]: 0x0
    ChannelDelay[5]: 0x0
    ChannelDelay[6]: 0x0
    ChannelDelay[7]: 0x0
    FrameDelay: 0x0
    Invert: False
  Ad9249Readout[3]:
    enable: False
    ChannelDelay[0]: 0x0
    ChannelDelay[1]: 0x0
    ChannelDelay[2]: 0x0
    ChannelDelay[3]: 0x0
    ChannelDelay[4]: 0x0
    ChannelDelay[5]: 0x0
    ChannelDelay[6]: 0x0
    ChannelDelay[7]: 0x0
    FrameDelay: 0x0
    Invert: False
  Ad9249Readout[4]:
    enable: False
    ChannelDelay[0]: 0x0
    ChannelDelay[1]: 0x0
    ChannelDelay[2]: 0x0
    ChannelDelay[3]: 0x0
    ChannelDelay[4]: 0x0
    ChannelDelay[5]: 0x0
    ChannelDelay[6]: 0x0
    ChannelDelay[7]: 0x0
    FrameDelay: 0x0
    Invert: False
  Ad9249Readout[5]:
    enable: False
    ChannelDelay[0]: 0x0
    ChannelDelay[1]: 0x0
    ChannelDelay[2]: 0x0
    ChannelDelay[3]: 0x0
    ChannelDelay[4]: 0x0
    ChannelDelay[5]: 0x0
    ChannelDelay[6]: 0x0
    ChannelDelay[7]: 0x0
    FrameDelay: 0x0
    Invert: False
  Ad9249Readout[6]:
    enable: False
    ChannelDelay[0]: 0x0
    ChannelDelay[1]: 0x0
    ChannelDelay[2]: 0x0
    ChannelDelay[3]: 0x0
    ChannelDelay[4]: 0x0
    ChannelDelay[5]: 0x0
    ChannelDelay[6]: 0x0
    ChannelDelay[7]: 0x0
    FrameDelay: 0x0
    Invert: False
  Ad9249Readout[7]:
    enable: False
    ChannelDelay[0]: 0x0
    ChannelDelay[1]: 0x0
    ChannelDelay[2]: 0x0
    ChannelDelay[3]: 0x0
    ChannelDelay[4]: 0x0
    ChannelDelay[5]: 0x0
    ChannelDelay[6]: 0x0
    ChannelDelay[7]: 0x0
    FrameDelay: 0x0
    Invert: False
  Ad9249Readout[8]:
    enable: False
    ChannelDelay[0]: 0x0
    ChannelDelay[1]: 0x0
    ChannelDelay[2]: 0x0
    ChannelDelay[3]: 0x0
    ChannelDelay[4]: 0x0
    ChannelDelay[5]: 0x0
    ChannelDelay[6]: 0x0
    ChannelDelay[7]: 0x0
    FrameDelay: 0x0
    Invert: False
  Ad9249Readout[9]:
    enable: False
    ChannelDelay[0]: 0x0
    ChannelDelay[1]: 0x0
    ChannelDelay[2]: 0x0
    ChannelDelay[3]: 0x0
    ChannelDelay[4]: 0x0
    ChannelDelay[5]: 0x0
    ChannelDelay[6]: 0x0
    ChannelDelay[7]: 0x0
    FrameDelay: 0x0
    Invert: False
  Ad9249Tester:
    enable: False
    TestChannel: 0x0
    TestDataMask: 0x0
    TestPattern: 0x0
    TestSamples: 0x0
    TestTimeout: 0x0
    TestRequest: False
  CypressS25Fl:
    enable: True
